# Generated by Django 3.0.1 on 2020-01-03 10:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(choices=[('SC', 'Secretary'), ('JS', 'Joint Secretary'), ('US', 'Under Secretary'), ('SO', 'Section Officer'), ('AO', 'Assistant Officer')], default='SO', max_length=2)),
                ('position_service', models.CharField(choices=[('AD', 'Administration'), ('EN', 'Engineering'), ('LG', 'Law'), ('MS', 'Miscellaneous'), ('SE', 'Cabinet')], max_length=200)),
                ('position_group', models.CharField(blank=True, max_length=200, null=True)),
                ('position_subgroup', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_lastname', models.CharField(max_length=200)),
                ('employee_firstname', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('employee_cv', models.FileField(blank=True, default='/media/resumes/django.pdf', null=True, upload_to='resumes')),
                ('employee_photo', models.ImageField(blank=True, default='/media/photos/test_image.png', null=True, upload_to='photos')),
                ('employee_dob', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date_of_birth')),
                ('employee_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsasd5.Position')),
            ],
        ),
    ]
