# Generated by Django 3.0.8 on 2020-07-20 08:49

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_path', models.FileField(blank=True, default='/media/documents/django.pdf', null=True, upload_to='documents')),
                ('document_category', models.CharField(choices=[('LAW', 'ऐन'), ('TN', 'टेन्डर आव्ह्वान'), ('OD', 'अन्य दस्तावेजहरु')], default='OD', max_length=50)),
                ('document_title', models.CharField(max_length=200)),
                ('document_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('published_date', models.DateTimeField()),
                ('short_text', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(choices=[('1CH', 'डिभिजन प्रमुख'), ('2SE', 'सुई'), ('3SDE', 'सिडिई'), ('4ERE', 'ईन्जिनियर आठौं'), ('5ERS', 'ईन्जिनियर सातौं'), ('6AOS', 'प्रशासन अधिकृत छैठौं'), ('7ACOS', 'लेखा अधिकृत छैठौं'), ('8CO', 'कम्प्युटर अधिकृत छैठौं'), ('9OT', 'अधिकृत छैठौं'), ('10SUBE', 'सब ईन्जिनियर'), ('11TEC', 'खा पा स टे')], default='5ERS', max_length=10)),
                ('position_service', models.CharField(choices=[('AD', 'Administration'), ('EN', 'Engineering'), ('LG', 'Law'), ('ACC', 'Account'), ('MSC', 'Miscellaneous')], max_length=200)),
                ('position_group', models.CharField(blank=True, max_length=200, null=True)),
                ('position_subgroup', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_lastname', models.CharField(max_length=200)),
                ('employee_firstname', models.CharField(max_length=200)),
                ('employee_section', models.CharField(default=' ', max_length=100)),
                ('employee_telephone', models.CharField(default=' ', max_length=10)),
                ('employee_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsasd5.Position')),
            ],
        ),
    ]
