# Generated by Django 3.0.8 on 2020-07-13 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsasd5', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_path', models.FileField(blank=True, default='/media/documents/django.pdf', null=True, upload_to='documents')),
                ('document_title', models.CharField(choices=[('LAW', 'ऐन'), ('TN', 'टेन्डर आव्ह्वान'), ('OD', 'अन्य दस्तावेजहरु')], default='OD', max_length=200)),
                ('document_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date created')),
            ],
        ),
    ]
