# Generated by Django 3.0.8 on 2020-07-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsasd5', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_section',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_telephone',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
