# Generated by Django 3.0.8 on 2020-07-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsasd5', '0004_auto_20200715_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_category',
            field=models.CharField(choices=[('LAW', 'ऐन'), ('TN', 'टेन्डर आव्ह्वान'), ('OD', 'अन्य दस्तावेजहरु')], default='OD', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_title',
            field=models.CharField(max_length=200),
        ),
    ]
