# Generated by Django 3.0.8 on 2020-07-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsasd5', '0005_auto_20200715_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_cv',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_dob',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_photo',
        ),
        migrations.AlterField(
            model_name='position',
            name='position_service',
            field=models.CharField(choices=[('AD', 'Administration'), ('EN', 'Engineering'), ('LG', 'Law'), ('ACC', 'Account'), ('MSC', 'Miscellaneous')], max_length=200),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_title',
            field=models.CharField(choices=[('1CH', 'डिभिजन प्रमुख'), ('2SE', 'सुई'), ('3SDE', 'सिडिई'), ('4ERE', 'ईन्जिनियर आठौं'), ('5ERS', 'ईन्जिनियर सातौं'), ('6AOS', 'प्रशासन अधिकृत छैठौं'), ('7ACOS', 'लेखा अधिकृत छैठौं'), ('8CO', 'कम्प्युटर अधिकृत छैठौं'), ('9OT', 'अधिकृत छैठौं'), ('10SUBE', 'सब ईन्जिनियर'), ('11TEC', 'खा पा स टे')], default='5ERS', max_length=10),
        ),
    ]
